Runner download: properly handle download cancel action
Actually we are rising an exception if user press the cancel button during
a download. This happen because Lutris does not check if files are really
downloaded, and tries to extract them even when the download is canceled.
This commit fixes that wrong behaviour checking if download is successful
before try extraction and removing the Exception in on_install_clicked
because in download canceled case self.runner.is_installed() is False, and
everything else (failed decompression, wrong installs, etc)
should be handled elsewhere

Fix:
DEBUG    2024-11-06 10:27:51,205 [download_progress_box.on_cancel_clicked:124]:Download cancel requested
DEBUG    2024-11-06 10:27:51,206 [downloader.cancel:118]:❌ https://github.com/Korkman/macemu-appimage-builder/releases/download/continuous/BasiliskII-x86_64.AppImage
DEBUG    2024-11-06 10:27:51,209 [downloader.cancel:118]:❌ https://github.com/Korkman/macemu-appimage-builder/releases/download/continuous/BasiliskII-x86_64.AppImage
ERROR    2024-11-06 10:27:51,219 [exception_backstops.error_wrapper:81]:Error handling signal 'clicked': Failed to extract /home/b--b/.cache/lutris/BasiliskII-x86_64.AppImage
Traceback (most recent call last):
  File "/media/NVME/lutris/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/NVME/lutris/lutris/gui/config/runner_box.py", line 95, in on_install_clicked
    self.runner.install(self.get_toplevel())
  File "/media/NVME/lutris/lutris/runners/runner.py", line 492, in install
    return self.download_and_extract(self.download_url, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/NVME/lutris/lutris/runners/runner.py", line 525, in download_and_extract
    self.extract(archive=runner_archive, dest=dest, merge_single=merge_single, callback=callback)
  File "/media/NVME/lutris/lutris/runners/runner.py", line 529, in extract
    raise RunnerInstallationError(_("Failed to extract {}").format(archive))
lutris.runners.RunnerInstallationError: Failed to extract /home/b--b/.cache/lutris/BasiliskII-x86_64.AppImage

Test: started and canceled a download, no more exceptions raised

Signed-off-by: Marco Zanin <mrczn.bb@gmail.com>